# 1. Беремо веб-сервер у світі (Nginx)
FROM nginx:alpine

# 2. Копіюємо твій файл index.html всередину контейнера
COPY index.html /usr/share/nginx/html/index.html

# 3. Відкриваємо порт 80 (стандарт для сайтів)
EXPOSE 80